### ISSUE TITLE
Correction to README for installing Python dependencies on macOS

### ISSUE THREAD

**Issue by garich** [krazynez/PSvid#1]
Hi,

I noticed that the README suggests running brew install python3-tk, but this didn't work for me. Instead, I used brew install python-tk, which worked. After this, I was able to run ./psvid.pyw without any errors.

Additionally, I also had to run brew install ffmpeg.

**Comment by krazynez** [comment]
Okay thanks will update. MacOS steps were pre-me forking.

Updated thanks 👍
